/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import main.Main;
import java.util.Calendar;
import java.util.Date;
import persistence.DBConnection;
import persistence.OSPersistence;

/**
 *
 * @author agomez
 */
public class OSForm extends javax.swing.JFrame {

    /**
     * Creates new form FormPersistenceGUI
     */
    public OSForm() {
        initComponents();
        //Añado un método para personalizar la inicialización de componentes
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_wrapper = new javax.swing.JTabbedPane();
        tab_or = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_input1 = new javax.swing.JTextField();
        cb_input2 = new javax.swing.JComboBox();
        tf_input3 = new javax.swing.JFormattedTextField();
        lbl_debug = new javax.swing.JLabel();
        tab_vehicleParts = new javax.swing.JPanel();
        lbl_model = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setText("Input prueba 1");

        jLabel3.setText("Input prueba 2");

        jLabel4.setText("Input prueba 3");

        tf_input1.setText("jTextField1");

        tf_input3.setEditable(false);
        tf_input3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY/MM/dd hh:mm:ss"))));

        lbl_debug.setText("Deb ug");

        javax.swing.GroupLayout tab_orLayout = new javax.swing.GroupLayout(tab_or);
        tab_or.setLayout(tab_orLayout);
        tab_orLayout.setHorizontalGroup(
            tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_orLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_orLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_debug)
                .addGap(264, 264, 264))
        );

        tab_orLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb_input2, tf_input1, tf_input3});

        tab_orLayout.setVerticalGroup(
            tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_orLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(tab_orLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(lbl_debug)
                .addGap(101, 101, 101))
        );

        tab_orLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cb_input2, tf_input1, tf_input3});

        tab_wrapper.addTab("OR Data", tab_or);

        javax.swing.GroupLayout tab_vehiclePartsLayout = new javax.swing.GroupLayout(tab_vehicleParts);
        tab_vehicleParts.setLayout(tab_vehiclePartsLayout);
        tab_vehiclePartsLayout.setHorizontalGroup(
            tab_vehiclePartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        tab_vehiclePartsLayout.setVerticalGroup(
            tab_vehiclePartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        tab_wrapper.addTab("Visual car inspection", tab_vehicleParts);

        lbl_model.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lbl_model.setText("Modelo-Coche (MM/YYYY) >> OR");

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jButton2.setText("CLOSE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab_wrapper)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_model, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_save, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_model, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_wrapper)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_save, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        
//        System.out.println(tf_input1.getText() + "-" + cb_input2.getSelectedItem().toString() + "-" + tf_input3.getText());
    }//GEN-LAST:event_btn_saveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Cerramos conexion BD
        DBConnection.instance.disconnect();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OSForm().setVisible(true);
//            }
//        });
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox cb_input2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_debug;
    private javax.swing.JLabel lbl_model;
    private javax.swing.JPanel tab_or;
    private javax.swing.JPanel tab_vehicleParts;
    private javax.swing.JTabbedPane tab_wrapper;
    private javax.swing.JTextField tf_input1;
    private javax.swing.JFormattedTextField tf_input3;
    // End of variables declaration//GEN-END:variables

    private void customInit() {
        //Hacemos que aparezca en el centro de la pantalla
        this.setLocationRelativeTo(null);
        //El campo fecha se rellena con la fecha actual
        tf_input3.setValue(new Date());  
    }
    
    public void actualizarDatetimeField(){
        
    }
    
    //Metodo personalizado para establecer el controller como action listener
    public void bindActionListener(Controller controller){
        jButton2.addActionListener(controller);
        btn_save.addActionListener(controller);
    }
    
    public String getInput1(){
        return tf_input1.getText();
    }
    
    public String getInput2(){
        return cb_input2.getSelectedItem().toString();
    }
    
    public String getInput3(){
        return tf_input3.getText();
    }
    
    //Método para ocultar pestañas que solo el usuario admin debe poder ver
    public void removeNoAdminTabs(){
//        tab_wrapper.remove(0);
    }
    
    //Método para rellenar el desplegable de seleccionar operario al que 
    //asignar la orden
    public void fillAsignadoA(String[] usuarios){
        for (String usuario: usuarios){
            cb_input2.addItem(usuario);
        }
    }
}
